apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server-1
  template:
    metadata:
      labels:
        app: redis-server-1
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-server-1
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-server-service-1
spec:
  selector:
    app: redis-server-1
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  # type: LoadBalancer  # This makes it accessible externally

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-benchmark
  template:
    metadata:
      labels:
        app: redis-benchmark
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-server-1
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: redis-benchmark
          image: quay.io/bertinatto/redis-bench:v2
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 100; done"]
