apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  nodeName: ip-10-0-46-29.ec2.internal
  containers:
  - name: app
    image: quay.io/centos/centos:stream9
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /tmp/out.txt; sleep 5; done"]
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
